### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by superkaiy** [scanoss/engine#40] opened 2022-11-11 13:07 UTC
Hi, @mscasso-scanoss 

- Meet unexpected exceptions : "segmentation fault". What should I do for it?

![Screenshot from 2022-11-11 20-55-12](https://user-images.githubusercontent.com/45934483/201345023-4701b277-b759-4ee6-b387-9f62b9143f3f.png)

- "M" option means that it will look for NUMBER of different components in the scanning file (MAX 9), right? did I use it incorrectly?
![Screenshot from 2022-11-11 20-57-32](https://user-images.githubusercontent.com/45934483/201345658-983d7c4c-2e21-43be-aaa1-0b034e310b41.png)

- Is there any options which can help to looking for different snippets in the scanning file, and show all the matching parts of snippets. for examples: the scanning file lines 0 ~ 100 matches flask/cli.py(...),  lines 300 ~350 matches flask/ctx.py(...), and lines 500 ~ 570 matches docker/compose/project.py(...)

**Comment by mscasso-scanoss** [comment] 2022-11-14 11:16
Hi @superkaiy, thank you for reporting this. I was able to reproduce your problem. There is a bug and it will be fixed with a new release this week. I will let you know! Sorry for the inconvenience.

**Comment by mscasso-scanoss** [comment] 2022-11-16 18:57
Hi @superkaiy, sorry for the delay. Please pull from master and try again (version 5.0.5).
About your question, the parameter "-M" is the right way to look for more than one snippet. For example "scanoss -M5 file.c" will look for 5 snippets maximum in "file.c"
Please try it and let me know if it does what you are expecting.

**Comment by superkaiy** [comment] 2022-11-17 01:32
Hi @mscasso-scanoss ,
I updated scanoss, but still meet the exception "segmentation fault"
![Screenshot from 2022-11-17 09-29-09](https://user-images.githubusercontent.com/45934483/202331916-9cb58452-98b0-4ce7-819b-a61ceb873951.png)

**Comment by mscasso-scanoss** [comment] 2022-11-17 01:48
Sorry to hear that. Could you share your file with me? If you can't because it is a private code, you can send me the wfp of the file.

**Comment by superkaiy** [comment] 2022-11-17 01:55
Hi @mscasso-scanoss 
I mined it into my local DB with minr
[scanner_output.wfp.txt](https://github.com/scanoss/engine/files/10027037/scanner_output.wfp.txt)

**Comment by mscasso-scanoss** [comment] 2022-11-17 01:59
Okay, in that case please install "valgrind", run again and share the output:

valgrind scanoss -M2  file.c

**Comment by superkaiy** [comment] 2022-11-17 02:23
Hi @mscasso-scanoss 
The debug information is attached
[debug.txt](https://github.com/scanoss/engine/files/10027163/debug.txt)
[debug_detail.txt](https://github.com/scanoss/engine/files/10027165/debug_detail.txt)

**Comment by mscasso-scanoss** [comment] 2022-11-17 18:07
Hi @superkaiy , please pull one more time from master and test again. I have added some defensive code, the root of the problem is your KB setup.

Attached you will see the results (there is a json inside the zip file) I got in my system.
[M2_test.zip](https://github.com/scanoss/engine/files/10034357/M2_test.zip)

**Comment by superkaiy** [comment] 2022-11-18 03:42
Hi @mscasso-scanoss 
I pulled the latest code(commit ID: 6187f7d68f1da4a8f9ac0f02536e39330dfb0790), and It's OK now, THank your
I did not do any changes on KB, so I could not understand that the root of the problem is your KB setup. 
![Screenshot from 2022-11-18 11-33-58](https://user-images.githubusercontent.com/45934483/202611597-718ed9d0-4916-4d70-8688-1237ee6d87c1.png)

**Comment by mscasso-scanoss** [comment] 2022-11-18 13:11
That looks nice, I'm going to close this issue, please fill free to open a new-one if you need it.

There are some missing LDB's tables in your system, but anyway this tables are not mandatory, so it actually was a bug in the engine. Thank you very much for your contribution.

**Closed by mscasso-scanoss** 2022-11-18 13:11 UTC
